#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function usage {
  echo "" >&2
  echo "greenerthumb-run-plotter <host>" >&2
  echo "" >&2
  echo "greenerthumb-run-plotter runs a plotter which receives messages" >&2
  echo "from a single publisher." >&2
  echo "" >&2
  echo "Accepts the publisher host." >&2
  echo "" >&2
  exit 2
}

if (($# != 1)); then
  usage
fi

greenerthumb-bullhorn-pubsub-client "${1}" --reconnect-delay 5 |
	greenerthumb-fan --out 'bash -c greenerthumb-message-json' \
		         --in 'bash -c greenerthumb-plot' \
		         --in 'bash -c greenerthumb-log'
