#!/usr/bin/env python3
"""
rm-error-log rms the error-log of a deployed greenerthumb program at a remote
user and host.
"""

import sys
import subprocess


def run(cmd):
    return subprocess.check_output(
        cmd, shell=True, stderr=subprocess.STDOUT).decode('utf-8')


def rm_error_log(user, host):
    command = "ssh {}@{} 'cd /opt/greenerthumb; rm -f error.log'".format(
        user, host)
    try:
        run(command)
    except subprocess.CalledProcessError as exc:
        output = exc.output.decode('utf-8')
        print()
        print("Error with command '{}':".format(exc.cmd))
        print()
        print(output)


def usage():
    p = lambda *args, **kwargs: print(*args, file=sys.stderr, **kwargs)
    p('')
    p('./rm-error-log <user> <host>')
    p('')
    p('rm-error-log rms the error-log of a deployed greenerthumb program at a')
    p('remote user and host.')
    p('')
    p('An example is:')
    p('')
    p('    ./rm-error-log pi 192.168.1.100')
    p('')
    sys.exit(2)


if __name__ == '__main__':
    if len(sys.argv) != 3:
        usage()
    user = sys.argv[1]
    host = sys.argv[2]

    rm_error_log(user, host)
