#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function usage {
  echo "" >&2
  echo "./run-air <host>" >&2
  echo "" >&2
  echo "run-air device." >&2
  echo "" >&2
  echo "Accepts the host to publish on." >&2
  echo "" >&2
  exit 2
}

if (($# != 1)); then
  usage
fi

BROADCAT_PORT=35053
NAME='Air Temperature Sensor'

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

greenerthumb-disclosure "${1}" |
	greenerthumb-message-header 'Disclosure' "${NAME}" |
	greenerthumb-message-bytes |
	greenerthumb-bullhorn-yell ${BROADCAT_PORT} &

greenerthumb-sense-air |
	greenerthumb-message-header 'Air' "${NAME}" |
	greenerthumb-message-bytes |
	greenerthumb-bullhorn-publish --host "${1}"
