#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function usage {
  echo "run-plotter and logger from bullhorn/subscribe." >&2
  echo "" >&2
  echo "Accepts the publisher host and port." >&2
  echo "" >&2
  exit 2
}

if (($# != 2)); then
  usage
fi

greenerthumb-bullhorn-subscribe ${1} ${2} | greenerthumb-fan \
	--out 'bash -c greenerthumb-message-json' \
	--in 'bash -c greenerthumb-plot' \
	--in 'bash -c greenerthumb-log'
