#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function usage {
  echo "" >&2
  echo "./run-soil <host>" >&2
  echo "" >&2
  echo "run-soil device." >&2
  echo "" >&2
  echo "Accepts the host to publish on." >&2
  echo "" >&2
  exit 2
}

if (($# != 1)); then
  usage
fi

BROADCAST_PORT=35053
NAME='Soil Moisture Sensor'

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

greenerthumb-disclosure "${1}" |
	greenerthumb-message-header 'Disclosure' "${NAME}" |
	greenerthumb-message-bytes |
	greenerthumb-bullhorn-broadcast-server ${BROADCAST_PORT} &

greenerthumb-sense-soil |
	greenerthumb-message-header 'Soil' "${NAME}" |
	greenerthumb-message-bytes |
	greenerthumb-bullhorn-pubsub-server --host "${1}"
