#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function usage {
  echo "" >&2
  echo "./run-disclosure <port> <host>" >&2
  echo "" >&2
  echo "run-disclosure into bullhorn/yell." >&2
  echo "" >&2
  echo "Accepts the port to yell on." >&2
  echo "" >&2
  exit 2
}

if (($# != 2)); then
  usage
fi

greenerthumb-disclosure "${2}" | greenerthumb-message-bytes |
	greenerthumb-bullhorn-yell "${1}"
