#!/usr/bin/env bash

function usage {
  echo "run_sensors into bullhorn/publish." >$2
  echo "" >$2
  echo "Accepts the port to publish on." >$2
  echo "" >$2
  exit 2
}

if (($# != 1)); then
  usage
fi

./build/fan/fan  \
  --in './build/sense/air' \
  --in './build/sense/soil' \
  --out './build/message/bytes' | ./build/bullhorn/publish ${1}
