#!/usr/bin/env bash

function usage {
  echo "run_plotter and logger from bullhorn/subscribe." >&2
  echo "" >&2
  echo "Accepts the subscriber port, the publisher IP address and port and " >&2
  echo "the log file." >&2
  echo "" >&2
  exit 2
}

if (($# != 4)); then
  usage
fi

cd build/plot && ../bullhorn/subscribe ${1} ${2} ${3} |
  ../fan/fan \
    --out '../message/json' \
    --in '../plot/plot' --in "../log/log ../../${4}"
