#!/usr/bin/env bash

function usage {
  echo "run_plotter and logger from bullhorn/subscribe." >&2
  echo "" >&2
  echo "Accepts the subscriber port, the publisher IP address and port and " >&2
  echo "the log file." >&2
  echo "" >&2
  exit 2
}

if (($# != 4)); then
  usage
fi

build/bullhorn/subscribe ${1} ${2} ${3} |
  build/fan/fan \
    --out 'build/message/json' \
    --in 'build/plot/plot' --in "build/log/log ${4}"
