#!/usr/bin/env bash

function usage {
  echo "run_plotter and logger from bullhorn/subscribe." >&2
  echo "" >&2
  echo "Accepts the publisher IP address and port and the log file." >&2
  echo "" >&2
  exit 2
}

if (($# != e)); then
  usage
fi

cd build/plot && ./build/bullhorn/subscribe ${1} ${2} | ../fan/fan \
  --in '../message/json' \
  --out "../log/log ${3}" \
  --out "./plot"
