#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function usage {
  echo "run_sensors into bullhorn/publish." >&2
  echo "" >&2
  echo "Accepts the port to publish on." >&2
  echo "" >&2
  exit 2
}

if (($# != 1)); then
  usage
fi

./build/fan/fan  \
  --out './build/sense/air' \
  --out './build/sense/soil' \
  --in './build/message/bytes' | ./build/bullhorn/publish ${1}
