#!/usr/bin/env bash

function usage {
  echo "run_air sensor into bullhorn/publish." >&2
  echo "" >&2
  echo "Accepts the port to publish on." >&2
  echo "" >&2
  exit 2
}

if (($# != 1)); then
  usage
fi

./build/sense/air | ./build/message/bytes | ./build/bullhorn/publish ${1}
