#!/usr/bin/env bash
#
# test is a convenience script to run all the sub-components tests.

set -e
set -u
set -o pipefail

test_subcomponent() {
	echo "testing $1"
	cd build/$1 && ./test && cd ../..
}

test_subcomponent fan
test_subcomponent bullhorn
test_subcomponent message
test_subcomponent process
test_subcomponent store
test_subcomponent plot
test_subcomponent disclosure
