#!/usr/bin/env bash
#
# test is a convenience script to run all the sub-components tests.

test_subcomponent() {
	echo "testing $1"
	cd build/$1 && ./test && cd ../..
}

test_subcomponent fan
test_subcomponent bullhorn
test_subcomponent message
