#!/usr/bin/env bash
#
# test is a convenience script to run all message program tests.

set -e
set -u
set -o pipefail

test_subcomponent() {
        echo "testing $1"
        cd $1 && ./test && cd ../
}

test_subcomponent header
test_subcomponent bytes
test_subcomponent json
