#!/usr/bin/env bash

set -e
set -u
set -o pipefail

function usage {
  echo "" >&2
  echo "greenerthumb-run-logger <host>" >&2
  echo "" >&2
  echo "greenerthumb-run-logger runs a logger which receives messages from." >&2
  echo "a single publisher." >&2
  echo "" >&2
  echo "Accepts the publisher host." >&2
  echo "" >&2
  exit 2
}

if (($# != 1)); then
  usage
fi

greenerthumb-bullhorn-pubsub-client "${1}" --reconnect-delay 5 |
	greenerthumb-message-json | greenerthumb-log
