#!/usr/bin/env python3

import argparse
import json
import random
import sys
import time


def emulate(rate):
    """emulate air temperature at the provided rate."""
    LOW = 60
    HIGH = 80
    MAX_DELTA = 0.5
    temperature = random.uniform(LOW, HIGH)
    while True:
        print(json.dumps({'Temperature': temperature}))
        multiplier = random.choice((-1, 1))
        delta = random.uniform(0, MAX_DELTA)
        temperature += multiplier * delta
        sys.stdout.flush()
        time.sleep(1 / rate)


if __name__ == '__main__':
    random.seed(time.time())

    RATE = 0.1

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--rate', default=RATE, type=float, help='rate to emulate')
    args = parser.parse_args()
    emulate(args.rate)
