#!/usr/bin/env python3

import argparse
import json
import sys
import time

import Adafruit_DHT


def to_fahrenheit(celsius):
    """to_fahrenheit converts the celsius temperature."""
    return celsius * 9 / 5 + 32


def sense(sensor, pin, rate):
    """
    sense temperature and humidity at the provided rate using the sensor, pin on
    the PI.
    """
    while True:
        humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)
        temperature = to_fahrenheit(temperature)
        print(json.dumps({
            'Name': 'Air',
            'Timestamp': int(time.time()),
            'Temperature': temperature,
            'Humidity': humidity
        }))
        sys.stdout.flush()
        time.sleep(1 / rate)


if __name__ == '__main__':
    RATE = 1
    PIN = 14  # BCM

    parser = argparse.ArgumentParser()
    parser.add_argument('--rate', default=RATE, type=int, help='rate to sense')
    parser.add_argument('--pin', default=PIN, type=int, help='pin number')
    args = parser.parse_args()

    sense(Adafruit_DHT.DHT22, args.pin, args.rate)
