#!/usr/bin/env python3

import argparse
import json
import random
import sys
import time


def emulate(rate):
    """emulate soil moisture at the provided rate."""
    MAX_DELTA = 0.05
    moisture = random.uniform(0, 1)
    while True:
        print(json.dumps({
            'Name': 'Soil',
            'Timestamp': int(time.time()),
            'Moisture': moisture
        }))
        multiplier = random.choice((-1, 1))
        delta = random.uniform(0, MAX_DELTA)
        moisture += multiplier * delta
        moisture = max(0, min(1, moisture))
        sys.stdout.flush()
        time.sleep(1 / rate)


if __name__ == '__main__':
    random.seed(time.time())

    RATE = 0.1

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--rate', default=RATE, type=float, help='rate to emulate')
    args = parser.parse_args()
    emulate(args.rate)
