all: sense

sense: emulate air soil

emulate: build
	cp emulate-air build/emulate-air
	cp emulate-soil build/emulate-soil

air: build
	cp air build/air

soil: build
	cp soil build/soil

build:
	mkdir -p build
