#!/usr/bin/env python3

import argparse
import json
import sys
import time

import Adafruit_MCP3008


def to_ratio(signal):
    """to_ratio converts the signal to a ratio."""
    LOW = 400  # LOW analog value indicating least dry.
    HIGH = 850  # HIGH analog value indicating most dry.
    return 1 - ((signal - LOW) / (HIGH - LOW))


def sense(sensor, channel, rate):
    """
    sense soil moisture at the provided rate using the sensor and the channel
    on the ADC.
    """
    while True:
        moisture = to_ratio(sensor.read_adc(channel))
        print(json.dumps({'Moisture': moisture}))
        sys.stdout.flush()
        time.sleep(1 / rate)


if __name__ == '__main__':
    RATE = 0.1

    # CHANNEL on the ADC.
    CHANNEL = 0

    # BCM
    CLK = 6
    MISO = 13
    MOSI = 19
    CS = 26

    parser = argparse.ArgumentParser()
    parser.add_argument('--rate', default=RATE, type=int, help='rate to sense')
    parser.add_argument(
        '--channel', default=CHANNEL, type=float, help='channel on ADC')
    parser.add_argument('--clk', default=CLK, help='clk pin number')
    parser.add_argument('--miso', default=MISO, help='miso pin number')
    parser.add_argument('--mosi', default=MOSI, help='mosi pin number')
    parser.add_argument('--cs', default=CS, help='cs pin number')
    args = parser.parse_args()

    sensor = Adafruit_MCP3008.MCP3008(
        clk=args.clk, cs=args.cs, miso=args.miso, mosi=args.mosi)

    sense(sensor, args.channel, args.rate)
